In [1]:
import requests
import pandas as pd

url = "https://qknhp8tc3y-dsn.algolia.net/1/indexes/produits_en/query"

headers = {
    "Accept": 'application/json',
    'Referer': 'https://www.instant-gaming.com/',
    'User-Agent':"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36",
    'content-type': 'application/x-www-form-urlencoded'
}

params = {
    "x-algolia-agent": "Algolia for vanilla JavaScript (lite) 3.24.7",
    "x-algolia-api-key": "4813969db52fc22897f8b84bac1299ad",
    "x-algolia-application-id": "QKNHP8TC3Y",
    "filter":"(sites:ig) AND (region:Worldwide OR region:SE OR region:Europe)"
}

payload={
    "query": "Hitman 3",
    "distinct": True,
    "hitsPerPage": 60,
}

response = requests.request("POST", url, headers=headers, json=payload, params=params)
#response.json()

In [2]:
response.json()['hits'][0]

{'lang': 'en',
 'name': 'Hitman 3',
 'prod_id': '6851',
 'seo_name': 'hitman-3-pc-game-epic-games-europe',
 'small_name': 'Hitman 3',
 'type': 'Epic Games',
 'region': 'Europe',
 'is_dlc': '0',
 'preorder': '0',
 'brand': 'Io-Interactive A/S',
 'is_draft': '0',
 'is_delivered': '1',
 'retail_currency': 'EUR',
 'other_platforms_prod_id': '8010,12619',
 'similar_prod_id': '',
 'promo': '0',
 'discount': 72,
 'currency_prices': {'EUR': 16.69,
  'USD': 16.69,
  'GBP': 16.69,
  'DKK': 16.69,
  'CHF': 16.69,
  'CAD': 16.69,
  'RSD': 16.69,
  'CZK': 16.69,
  'AUD': 16.69,
  'SEK': 16.69,
  'PLN': 16.69,
  'NOK': 16.69,
  'AED': 16.69,
  'BRL': 16.69},
 'sites': ['ig'],
 'sites_prices': {'ig': 16.69},
 'platforms': ['1'],
 'price': 16.69,
 'retail': '59.99',
 'category': ['Single-player', 'Action', 'Adventure'],
 'search_tags': ['Action',
  'Stealth',
  'VR',
  'Assassin',
  'Adventure',
  'Sandbox',
  'Shooter',
  'Third-Person Shooter',
  'Violent',
  'Third Person',
  'Cinematic',
  'Realistic',
  'Funny',
  'Gore',
  'Puzzle',
  'Capitalism',
  'Immersive Sim',
  'Open World',
  'Single-player',
  'Action',
  'Adventure'],
 'avail_date': 1642636800,
 'vpn_countries': None,
 'exclude_from_search': '0',
 'langs': ['cn', 'de', 'en', 'es', 'fr', 'it', 'jp', 'ru'],
 'manual_search_tags': None,
 'developer_id': '941',
 'publisher_id': '941',
 'is_free_to_play': '0',
 'updated_at': 1657198147,
 'has_video_preview': '1',
 'video_preview_updated_at': '1659126963',
 'is_prepaid': '0',
 'developer_name': 'Io-Interactive A/S',
 'publisher_name': 'Io-Interactive A/S',
 'can_display_video_preview': '1',
 'platform': 'Epic Games',
 'reviews_avg': 90,
 'cat_ids': ['47', '1', '4'],
 'lcat': 'H',
 'objectID': '6851',
 '_highlightResult': {'name': {'value': '<em>Hitman</em> <em>3</em>',
   'matchLevel': 'full',
   'fullyHighlighted': True,
   'matchedWords': ['hitman', '3']},
  'small_name': {'value': '<em>Hitman</em> <em>3</em>',
   'matchLevel': 'full',
   'fullyHighlighted': True,
   'matchedWords': ['hitman', '3']},
  'search_tags': [{'value': 'Action',
    'matchLevel': 'none',
    'matchedWords': []},
   {'value': 'Stealth', 'matchLevel': 'none', 'matchedWords': []},
   {'value': 'VR', 'matchLevel': 'none', 'matchedWords': []},
   {'value': 'Assassin', 'matchLevel': 'none', 'matchedWords': []},
   {'value': 'Adventure', 'matchLevel': 'none', 'matchedWords': []},
   {'value': 'Sandbox', 'matchLevel': 'none', 'matchedWords': []},
   {'value': 'Shooter', 'matchLevel': 'none', 'matchedWords': []},
   {'value': 'Third-Person Shooter', 'matchLevel': 'none', 'matchedWords': []},
   {'value': 'Violent', 'matchLevel': 'none', 'matchedWords': []},
   {'value': 'Third Person', 'matchLevel': 'none', 'matchedWords': []},
   {'value': 'Cinematic', 'matchLevel': 'none', 'matchedWords': []},
   {'value': 'Realistic', 'matchLevel': 'none', 'matchedWords': []},
   {'value': 'Funny', 'matchLevel': 'none', 'matchedWords': []},
   {'value': 'Gore', 'matchLevel': 'none', 'matchedWords': []},
   {'value': 'Puzzle', 'matchLevel': 'none', 'matchedWords': []},
   {'value': 'Capitalism', 'matchLevel': 'none', 'matchedWords': []},
   {'value': 'Immersive Sim', 'matchLevel': 'none', 'matchedWords': []},
   {'value': 'Open World', 'matchLevel': 'none', 'matchedWords': []},
   {'value': 'Single-player', 'matchLevel': 'none', 'matchedWords': []},
   {'value': 'Action', 'matchLevel': 'none', 'matchedWords': []},
   {'value': 'Adventure', 'matchLevel': 'none', 'matchedWords': []}],
  'developer_name': {'value': 'Io-Interactive A/S',
   'matchLevel': 'none',
   'matchedWords': []},
  'publisher_name': {'value': 'Io-Interactive A/S',
   'matchLevel': 'none',
   'matchedWords': []}}}

In [22]:
df_hitman=pd.json_normalize(response.json(),record_path=['hits'], max_level=0)
df_hitman.iloc[:,16:]

,discount,currency_prices,sites,sites_prices,platforms,price,retail,category,search_tags,avail_date,...,is_prepaid,developer_name,publisher_name,can_display_video_preview,platform,reviews_avg,cat_ids,lcat,objectID,_highlightResult
0,72,"{'EUR': 16.69, 'USD': 16.69, 'GBP': 16.69, 'DK...",[ig],{'ig': 16.69},[1],16.69,59.99,"[Single-player, Action, Adventure]","[Action, Stealth, VR, Assassin, Adventure, San...",1642636800,...,0,Io-Interactive A/S,Io-Interactive A/S,1,Epic Games,90,"[47, 1, 4]",H,6851,{'name': {'value': '<em>Hitman</em> <em>3</em>...
1,57,"{'EUR': 25.75, 'PLN': 23.26, 'USD': 25.75, 'GB...",[ig],{'ig': 25.75},[1],25.75,59.99,"[Single-player, Action, Adventure]","[Action, Stealth, VR, Assassin, Adventure, San...",1642636800,...,0,Io-Interactive A/S,Io-Interactive A/S,1,Steam,90,"[47, 1, 4]",H,12619,{'name': {'value': '<em>Hitman</em> <em>3</em>...
2,8,"{'EUR': 55.26, 'PLN': 56.46, 'USD': 55.26, 'GB...",[ig],{'ig': 55.26},"[11, 12]",55.26,59.99,"[Single-player, Action, Adventure]","[Action, Stealth, VR, Assassin, Adventure, San...",1642636800,...,0,Io-Interactive A/S,Io-Interactive A/S,1,Xbox Series X|S,90,"[47, 1, 4]",H,8010,{'name': {'value': '<em>Hitman</em> <em>3</em>...

In [4]:
df_hitman.keys()

Index(['lang', 'name', 'prod_id', 'seo_name', 'small_name', 'type', 'region',
       'is_dlc', 'preorder', 'brand', 'is_draft', 'is_delivered',
       'retail_currency', 'other_platforms_prod_id', 'similar_prod_id',
       'promo', 'discount', 'currency_prices', 'sites', 'sites_prices',
       'platforms', 'price', 'retail', 'category', 'search_tags', 'avail_date',
       'vpn_countries', 'exclude_from_search', 'langs', 'manual_search_tags',
       'developer_id', 'publisher_id', 'is_free_to_play', 'updated_at',
       'has_video_preview', 'video_preview_updated_at', 'is_prepaid',
       'developer_name', 'publisher_name', 'can_display_video_preview',
       'platform', 'reviews_avg', 'cat_ids', 'lcat', 'objectID',
       '_highlightResult'],
      dtype='object')

In [23]:
dfh=df_hitman.astype({'sites':str,"platforms":str})

In [27]:
json_data=response.json()['hits']
df_hitman_prices=pd.json_normalize(json_data,max_level=1)
df_hitman_prices.dtypes

df_hitman_prices.values[0][10:]

array(['0', '1', 'EUR', '8010,12619', '', '0', 72, list(['ig']),
       list(['1']), 16.69, '59.99',
       list(['Single-player', 'Action', 'Adventure']),
       list(['Action', 'Stealth', 'VR', 'Assassin', 'Adventure', 'Sandbox', 'Shooter', 'Third-Person Shooter', 'Violent', 'Third Person', 'Cinematic', 'Realistic', 'Funny', 'Gore', 'Puzzle', 'Capitalism', 'Immersive Sim', 'Open World', 'Single-player', 'Action', 'Adventure']),
       1642636800, None, '0',
       list(['cn', 'de', 'en', 'es', 'fr', 'it', 'jp', 'ru']), None,
       '941', '941', '0', 1657198147, '1', '1659126963', '0',
       'Io-Interactive A/S', 'Io-Interactive A/S', '1', 'Epic Games', 90,
       list(['47', '1', '4']), 'H', '6851', 16.69, 16.69, 16.69, 16.69,
       16.69, 16.69, 16.69, 16.69, 16.69, 16.69, 16.69, 16.69, 16.69,
       16.69, 16.69,
       {'value': '<em>Hitman</em> <em>3</em>', 'matchLevel': 'full', 'fullyHighlighted': True, 'matchedWords': ['hitman', '3']},
       {'value': '<em>Hitman</em> <em>3</em>', 'matchLevel': 'full', 'fullyHighlighted': True, 'matchedWords': ['hitman', '3']},
       list([{'value': 'Action', 'matchLevel': 'none', 'matchedWords': []}, {'value': 'Stealth', 'matchLevel': 'none', 'matchedWords': []}, {'value': 'VR', 'matchLevel': 'none', 'matchedWords': []}, {'value': 'Assassin', 'matchLevel': 'none', 'matchedWords': []}, {'value': 'Adventure', 'matchLevel': 'none', 'matchedWords': []}, {'value': 'Sandbox', 'matchLevel': 'none', 'matchedWords': []}, {'value': 'Shooter', 'matchLevel': 'none', 'matchedWords': []}, {'value': 'Third-Person Shooter', 'matchLevel': 'none', 'matchedWords': []}, {'value': 'Violent', 'matchLevel': 'none', 'matchedWords': []}, {'value': 'Third Person', 'matchLevel': 'none', 'matchedWords': []}, {'value': 'Cinematic', 'matchLevel': 'none', 'matchedWords': []}, {'value': 'Realistic', 'matchLevel': 'none', 'matchedWords': []}, {'value': 'Funny', 'matchLevel': 'none', 'matchedWords': []}, {'value': 'Gore', 'matchLevel': 'none', 'matchedWords': []}, {'value': 'Puzzle', 'matchLevel': 'none', 'matchedWords': []}, {'value': 'Capitalism', 'matchLevel': 'none', 'matchedWords': []}, {'value': 'Immersive Sim', 'matchLevel': 'none', 'matchedWords': []}, {'value': 'Open World', 'matchLevel': 'none', 'matchedWords': []}, {'value': 'Single-player', 'matchLevel': 'none', 'matchedWords': []}, {'value': 'Action', 'matchLevel': 'none', 'matchedWords': []}, {'value': 'Adventure', 'matchLevel': 'none', 'matchedWords': []}]),
       {'value': 'Io-Interactive A/S', 'matchLevel': 'none', 'matchedWords': []},
       {'value': 'Io-Interactive A/S', 'matchLevel': 'none', 'matchedWords': []}],
      dtype=object)

In [6]:
import sqlite3 as db
import sqlalchemy as dba

In [7]:
engine = dba.create_engine('sqlite:///gameprices.db', echo=True)
sqlite_connection = engine.connect()

In [8]:

conn=db.connect('gameprices.db')
c=conn.cursor()

In [9]:
#c.execute("CREATE TABLE employees (empid INTEGER PRIMARY KEY, firstname NVARCHAR(20), lastname NVARCHAR(20))")

In [10]:
#c.execute("INSERT INTO employees VALUES (12986,'Michael','Scott')")
#c.execute("INSERT INTO employees VALUES (12987,'Dwight','Schrute')")

In [11]:
new_employees = [
    (12994, 'Jim', 'Halpert'), 
    (12988, 'Pam', 'Beesly'), 
    (12989, 'Andy', 'Bernard'), 
    (12990, 'Kevin', 'Malone'),
    (12991, 'Toby', 'Flenderson'),
    (12992, 'Angela', 'Martin'),
    (12993, 'Stanley', 'Hudson')]

c.executemany('INSERT INTO employees VALUES (?, ?, ?)', new_employees)

OperationalError: no such table: employees

In [ ]:
c.execute("SELECT * FROM employees")
print(c.fetchall())

[(0, 0, 12986, 'Michael', 'Scott'), (1, 1, 12987, 'Dwight', 'Schrute'), (2, 2, 12988, 'Pam', 'Beesly'), (3, 3, 12989, 'Andy', 'Bernard'), (4, 4, 12990, 'Kevin', 'Malone'), (5, 5, 12991, 'Toby', 'Flenderson'), (6, 6, 12992, 'Angela', 'Martin')]

In [ ]:
con = db.connect('gameprices.db')
df_employees = pd.read_sql_query('select * from employees', con)
df_employees

   level_0  index  empid firstname    lastname
0        0      0  12986   Michael       Scott
1        1      1  12987    Dwight     Schrute
2        2      2  12988       Pam      Beesly
3        3      3  12989      Andy     Bernard
4        4      4  12990     Kevin      Malone
5        5      5  12991      Toby  Flenderson
6        6      6  12992    Angela      Martin

df_new = df_employees[:-1]

df_new.to_sql("employees", con, if_exists="replace")

In [28]:
df_hitman.iloc[:,17:]

,currency_prices,sites,sites_prices,platforms,price,retail,category,search_tags,avail_date,vpn_countries,...,is_prepaid,developer_name,publisher_name,can_display_video_preview,platform,reviews_avg,cat_ids,lcat,objectID,_highlightResult
0,"{'EUR': 16.69, 'USD': 16.69, 'GBP': 16.69, 'DK...",[ig],{'ig': 16.69},[1],16.69,59.99,"[Single-player, Action, Adventure]","[Action, Stealth, VR, Assassin, Adventure, San...",1642636800,None,...,0,Io-Interactive A/S,Io-Interactive A/S,1,Epic Games,90,"[47, 1, 4]",H,6851,{'name': {'value': '<em>Hitman</em> <em>3</em>...
1,"{'EUR': 25.75, 'PLN': 23.26, 'USD': 25.75, 'GB...",[ig],{'ig': 25.75},[1],25.75,59.99,"[Single-player, Action, Adventure]","[Action, Stealth, VR, Assassin, Adventure, San...",1642636800,None,...,0,Io-Interactive A/S,Io-Interactive A/S,1,Steam,90,"[47, 1, 4]",H,12619,{'name': {'value': '<em>Hitman</em> <em>3</em>...
2,"{'EUR': 55.26, 'PLN': 56.46, 'USD': 55.26, 'GB...",[ig],{'ig': 55.26},"[11, 12]",55.26,59.99,"[Single-player, Action, Adventure]","[Action, Stealth, VR, Assassin, Adventure, San...",1642636800,None,...,0,Io-Interactive A/S,Io-Interactive A/S,1,Xbox Series X|S,90,"[47, 1, 4]",H,8010,{'name': {'value': '<em>Hitman</em> <em>3</em>...

In [30]:
df_hitman.to_csv('steam_data',index=False)

In [25]:
#con = db.connect('gameprices.db')
dfh.to_sql('steam_games', sqlite_connection, if_exists="replace", index=False,dtype={"currency_prices": dba.types.JSON,"sites_prices":dba.types.ARRAY(dba.types.INT())})

2022-10-18 17:43:14,293 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("steam_games")
2022-10-18 17:43:14,294 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-18 17:43:14,295 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("steam_games")
2022-10-18 17:43:14,295 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-18 17:43:14,297 INFO sqlalchemy.engine.Engine SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
2022-10-18 17:43:14,297 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-18 17:43:14,299 INFO sqlalchemy.engine.Engine PRAGMA main.table_xinfo("steam_games")
2022-10-18 17:43:14,299 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-18 17:43:14,301 INFO sqlalchemy.engine.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'
2022-10-18 17:43:14,302 INFO sqlalchemy.engine.Engine [raw sql] ('steam_games',)
2022-10-18 17:43:14,303 INFO sqlalchemy.engine.Engine PRAGMA main.foreign_key_list("steam_games")
2022-10-18 17:43:14,304 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-18 17:43:14,304 INFO sqlalchemy.engine.Engine PRAGMA temp.foreign_key_list("steam_games")
2022-10-18 17:43:14,304 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-18 17:43:14,305 INFO sqlalchemy.engine.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'
2022-10-18 17:43:14,305 INFO sqlalchemy.engine.Engine [raw sql] ('steam_games',)
2022-10-18 17:43:14,307 INFO sqlalchemy.engine.Engine PRAGMA main.index_list("steam_games")
2022-10-18 17:43:14,307 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-18 17:43:14,308 INFO sqlalchemy.engine.Engine PRAGMA temp.index_list("steam_games")
2022-10-18 17:43:14,308 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-18 17:43:14,310 INFO sqlalchemy.engine.Engine PRAGMA main.index_list("steam_games")
2022-10-18 17:43:14,310 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-18 17:43:14,311 INFO sqlalchemy.engine.Engine PRAGMA temp.index_list("steam_games")
2022-10-18 17:43:14,311 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-10-18 17:43:14,312 INFO sqlalchemy.engine.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'
2022-10-18 17:43:14,312 INFO sqlalchemy.engine.Engine [raw sql] ('steam_games',)
2022-10-18 17:43:14,314 INFO sqlalchemy.engine.Engine
DROP TABLE steam_games
2022-10-18 17:43:14,314 INFO sqlalchemy.engine.Engine [no key 0.00043s] ()
2022-10-18 17:43:14,327 INFO sqlalchemy.engine.Engine COMMIT
2022-10-18 17:43:14,330 INFO sqlalchemy.engine.Engine
CREATE TABLE steam_games (
	lang TEXT,
	name TEXT,
	prod_id TEXT,
	seo_name TEXT,
	small_name TEXT,
	type TEXT,
	region TEXT,
	is_dlc TEXT,
	preorder TEXT,
	brand TEXT,
	is_draft TEXT,
	is_delivered TEXT,
	retail_currency TEXT,
	other_platforms_prod_id TEXT,
	similar_prod_id TEXT,
	promo TEXT,
	discount BIGINT,
	currency_prices JSON,
	sites TEXT,
	sites_prices TEXT,
	platforms TEXT,
	price FLOAT,
	retail TEXT,
	category TEXT,
	search_tags TEXT,
	avail_date BIGINT,
	vpn_countries TEXT,
	exclude_from_search TEXT,
	langs TEXT,
	manual_search_tags TEXT,
	developer_id TEXT,
	publisher_id TEXT,
	is_free_to_play TEXT,
	updated_at BIGINT,
	has_video_preview TEXT,
	video_preview_updated_at TEXT,
	is_prepaid TEXT,
	developer_name TEXT,
	publisher_name TEXT,
	can_display_video_preview TEXT,
	platform TEXT,
	reviews_avg BIGINT,
	cat_ids TEXT,
	lcat TEXT,
	"objectID" TEXT,
	"_highlightResult" TEXT
)


2022-10-18 17:43:14,331 INFO sqlalchemy.engine.Engine [no key 0.00083s] ()
2022-10-18 17:43:14,346 INFO sqlalchemy.engine.Engine COMMIT
2022-10-18 17:43:14,349 INFO sqlalchemy.engine.Engine INSERT INTO steam_games (lang, name, prod_id, seo_name, small_name, type, region, is_dlc, preorder, brand, is_draft, is_delivered, retail_currency, other_platforms_prod_id, similar_prod_id, promo, discount, currency_prices, sites, sites_prices, platforms, price, retail, category, search_tags, avail_date, vpn_countries, exclude_from_search, langs, manual_search_tags, developer_id, publisher_id, is_free_to_play, updated_at, has_video_preview, video_preview_updated_at, is_prepaid, developer_name, publisher_name, can_display_video_preview, platform, reviews_avg, cat_ids, lcat, "objectID", "_highlightResult") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2022-10-18 17:43:14,350 INFO sqlalchemy.engine.Engine [generated in 0.00127s] (('en', 'Hitman 3', '6851', 'hitman-3-pc-game-epic-games-europe', 'Hitman 3', 'Epic Games', 'Europe', '0', '0', 'Io-Interactive A/S', '0', '1', 'EUR', '8010,12619', '', '0', 72, '{"EUR": 16.69, "USD": 16.69, "GBP": 16.69, "DKK": 16.69, "CHF": 16.69, "CAD": 16.69, "RSD": 16.69, "CZK": 16.69, "AUD": 16.69, "SEK": 16.69, "PLN": 16.69, "NOK": 16.69, "AED": 16.69, "BRL": 16.69}', "['ig']", {'ig': 16.69}, "['1']", 16.69, '59.99', ['Single-player', 'Action', 'Adventure'], ['Action', 'Stealth', 'VR', 'Assassin', 'Adventure', 'Sandbox', 'Shooter', 'Third-Person Shooter', 'Violent', 'Third Person', 'Cinematic', 'Realistic', 'Funny', 'Gore', 'Puzzle', 'Capitalism', 'Immersive Sim', 'Open World', 'Single-player', 'Action', 'Adventure'], 1642636800, None, '0', ['cn', 'de', 'en', 'es', 'fr', 'it', 'jp', 'ru'], None, '941', '941', '0', 1657198147, '1', '1659126963', '0', 'Io-Interactive A/S', 'Io-Interactive A/S', '1', 'Epic Games', 90, ['47', '1', '4'], 'H', '6851', {'name': {'value': '<em>Hitman</em> <em>3</em>', 'matchLevel': 'full', 'fullyHighlighted': True, 'matchedWords': ['hitman', '3']}, 'small_name': {'val ... (1545 characters truncated) ... eractive A/S', 'matchLevel': 'none', 'matchedWords': []}, 'publisher_name': {'value': 'Io-Interactive A/S', 'matchLevel': 'none', 'matchedWords': []}}), ('en', 'Hitman 3', '12619', 'hitman-3-pc-game-steam', 'Hitman 3', 'Steam', 'Worldwide', '0', '0', 'Io-Interactive A/S', '0', '1', 'EUR', '6851,8010', '', '0', 57, '{"EUR": 25.75, "PLN": 23.26, "USD": 25.75, "GBP": 25.75, "DKK": 25.75, "CHF": 25.75, "CAD": 25.75, "RSD": 25.75, "CZK": 25.75, "AUD": 25.75, "SEK": 25.75, "NOK": 25.75, "AED": 25.75, "BRL": 25.75}', "['ig']", {'ig': 25.75}, "['1']", 25.75, '59.99', ['Single-player', 'Action', 'Adventure'], ['Action', 'Stealth', 'VR', 'Assassin', 'Adventure', 'Sandbox', 'Shooter', 'Third-Person Shooter', 'Violent', 'Third Person', 'Cinematic', 'Realistic', 'Funny', 'Gore', 'Puzzle', 'Capitalism', 'Immersive Sim', 'Open World', 'Single-player', 'Action', 'Adventure'], 1642636800, None, '0', ['cn', 'de', 'en', 'es', 'fr', 'it', 'jp', 'ru'], None, '941', '941', '0', 1659079811, '1', '1659126963', '0', 'Io-Interactive A/S', 'Io-Interactive A/S', '1', 'Steam', 90, ['47', '1', '4'], 'H', '12619', {'name': {'value': '<em>Hitman</em> <em>3</em>', 'matchLevel': 'full', 'fullyHighlighted': True, 'matchedWords': ['hitman', '3']}, 'small_name': {'val ... (1545 characters truncated) ... eractive A/S', 'matchLevel': 'none', 'matchedWords': []}, 'publisher_name': {'value': 'Io-Interactive A/S', 'matchLevel': 'none', 'matchedWords': []}}), ('en', 'Hitman 3 (Xbox ONE / Xbox Series X|S)', '8010', 'hitman-3-xbox-one-xbox-series-x-s-xbox-one-xbox-series-x-s-game-microsoft-store', 'Hitman 3 (Xbox ONE / Xbox Series X|S)', 'Microsoft Store', 'Worldwide', '0', '0', 'Io-Interactive A/S', '0', '1', 'EUR', '6851,12619', '', '0', 8, '{"EUR": 55.26, "PLN": 56.46, "USD": 55.26, "GBP": 55.26, "DKK": 55.26, "CHF": 55.26, "CAD": 55.26, "RSD": 55.26, "CZK": 55.26, "AUD": 55.26, "SEK": 55.26, "NOK": 55.26, "AED": 55.26, "BRL": 55.26}', "['ig']", {'ig': 55.26}, "['11', '12']", 55.26, '59.99', ['Single-player', 'Action', 'Adventure'], ['Action', 'Stealth', 'VR', 'Assassin', 'Adventure', 'Sandbox', 'Shooter', 'Third-Person Shooter', 'Violent', 'Third Person', 'Cinematic', 'Realistic', 'Funny', 'Gore', 'Puzzle', 'Capitalism', 'Immersive Sim', 'Open World', 'Single-player', 'Action', 'Adventure'], 1642636800, None, '0', ['cn', 'de', 'en', 'es', 'fr', 'it', 'jp', 'ru'], None, '941', '941', '0', 1657198095, '1', '1659126963', '0', 'Io-Interactive A/S', 'Io-Interactive A/S', '1', 'Xbox Series X|S', 90, ['47', '1', '4'], 'H', '8010', {'name': {'value': '<em>Hitman</em> <em>3</em> (Xbox ONE / Xbox Series X|S)', 'matchLevel': 'full', 'fullyHighlighted': False, 'matchedWords': ['hitma ... (1605 characters truncated) ... eractive A/S', 'matchLevel': 'none', 'matchedWords': []}, 'publisher_name': {'value': 'Io-Interactive A/S', 'matchLevel': 'none', 'matchedWords': []}}))
2022-10-18 17:43:14,351 INFO sqlalchemy.engine.Engine ROLLBACK

InterfaceError: (sqlite3.InterfaceError) Error binding parameter 19 - probably unsupported type.
[SQL: INSERT INTO steam_games (lang, name, prod_id, seo_name, small_name, type, region, is_dlc, preorder, brand, is_draft, is_delivered, retail_currency, other_platforms_prod_id, similar_prod_id, promo, discount, currency_prices, sites, sites_prices, platforms, price, retail, category, search_tags, avail_date, vpn_countries, exclude_from_search, langs, manual_search_tags, developer_id, publisher_id, is_free_to_play, updated_at, has_video_preview, video_preview_updated_at, is_prepaid, developer_name, publisher_name, can_display_video_preview, platform, reviews_avg, cat_ids, lcat, "objectID", "_highlightResult") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (('en', 'Hitman 3', '6851', 'hitman-3-pc-game-epic-games-europe', 'Hitman 3', 'Epic Games', 'Europe', '0', '0', 'Io-Interactive A/S', '0', '1', 'EUR', '8010,12619', '', '0', 72, '{"EUR": 16.69, "USD": 16.69, "GBP": 16.69, "DKK": 16.69, "CHF": 16.69, "CAD": 16.69, "RSD": 16.69, "CZK": 16.69, "AUD": 16.69, "SEK": 16.69, "PLN": 16.69, "NOK": 16.69, "AED": 16.69, "BRL": 16.69}', "['ig']", {'ig': 16.69}, "['1']", 16.69, '59.99', ['Single-player', 'Action', 'Adventure'], ['Action', 'Stealth', 'VR', 'Assassin', 'Adventure', 'Sandbox', 'Shooter', 'Third-Person Shooter', 'Violent', 'Third Person', 'Cinematic', 'Realistic', 'Funny', 'Gore', 'Puzzle', 'Capitalism', 'Immersive Sim', 'Open World', 'Single-player', 'Action', 'Adventure'], 1642636800, None, '0', ['cn', 'de', 'en', 'es', 'fr', 'it', 'jp', 'ru'], None, '941', '941', '0', 1657198147, '1', '1659126963', '0', 'Io-Interactive A/S', 'Io-Interactive A/S', '1', 'Epic Games', 90, ['47', '1', '4'], 'H', '6851', {'name': {'value': '<em>Hitman</em> <em>3</em>', 'matchLevel': 'full', 'fullyHighlighted': True, 'matchedWords': ['hitman', '3']}, 'small_name': {'val ... (1545 characters truncated) ... eractive A/S', 'matchLevel': 'none', 'matchedWords': []}, 'publisher_name': {'value': 'Io-Interactive A/S', 'matchLevel': 'none', 'matchedWords': []}}), ('en', 'Hitman 3', '12619', 'hitman-3-pc-game-steam', 'Hitman 3', 'Steam', 'Worldwide', '0', '0', 'Io-Interactive A/S', '0', '1', 'EUR', '6851,8010', '', '0', 57, '{"EUR": 25.75, "PLN": 23.26, "USD": 25.75, "GBP": 25.75, "DKK": 25.75, "CHF": 25.75, "CAD": 25.75, "RSD": 25.75, "CZK": 25.75, "AUD": 25.75, "SEK": 25.75, "NOK": 25.75, "AED": 25.75, "BRL": 25.75}', "['ig']", {'ig': 25.75}, "['1']", 25.75, '59.99', ['Single-player', 'Action', 'Adventure'], ['Action', 'Stealth', 'VR', 'Assassin', 'Adventure', 'Sandbox', 'Shooter', 'Third-Person Shooter', 'Violent', 'Third Person', 'Cinematic', 'Realistic', 'Funny', 'Gore', 'Puzzle', 'Capitalism', 'Immersive Sim', 'Open World', 'Single-player', 'Action', 'Adventure'], 1642636800, None, '0', ['cn', 'de', 'en', 'es', 'fr', 'it', 'jp', 'ru'], None, '941', '941', '0', 1659079811, '1', '1659126963', '0', 'Io-Interactive A/S', 'Io-Interactive A/S', '1', 'Steam', 90, ['47', '1', '4'], 'H', '12619', {'name': {'value': '<em>Hitman</em> <em>3</em>', 'matchLevel': 'full', 'fullyHighlighted': True, 'matchedWords': ['hitman', '3']}, 'small_name': {'val ... (1545 characters truncated) ... eractive A/S', 'matchLevel': 'none', 'matchedWords': []}, 'publisher_name': {'value': 'Io-Interactive A/S', 'matchLevel': 'none', 'matchedWords': []}}), ('en', 'Hitman 3 (Xbox ONE / Xbox Series X|S)', '8010', 'hitman-3-xbox-one-xbox-series-x-s-xbox-one-xbox-series-x-s-game-microsoft-store', 'Hitman 3 (Xbox ONE / Xbox Series X|S)', 'Microsoft Store', 'Worldwide', '0', '0', 'Io-Interactive A/S', '0', '1', 'EUR', '6851,12619', '', '0', 8, '{"EUR": 55.26, "PLN": 56.46, "USD": 55.26, "GBP": 55.26, "DKK": 55.26, "CHF": 55.26, "CAD": 55.26, "RSD": 55.26, "CZK": 55.26, "AUD": 55.26, "SEK": 55.26, "NOK": 55.26, "AED": 55.26, "BRL": 55.26}', "['ig']", {'ig': 55.26}, "['11', '12']", 55.26, '59.99', ['Single-player', 'Action', 'Adventure'], ['Action', 'Stealth', 'VR', 'Assassin', 'Adventure', 'Sandbox', 'Shooter', 'Third-Person Shooter', 'Violent', 'Third Person', 'Cinematic', 'Realistic', 'Funny', 'Gore', 'Puzzle', 'Capitalism', 'Immersive Sim', 'Open World', 'Single-player', 'Action', 'Adventure'], 1642636800, None, '0', ['cn', 'de', 'en', 'es', 'fr', 'it', 'jp', 'ru'], None, '941', '941', '0', 1657198095, '1', '1659126963', '0', 'Io-Interactive A/S', 'Io-Interactive A/S', '1', 'Xbox Series X|S', 90, ['47', '1', '4'], 'H', '8010', {'name': {'value': '<em>Hitman</em> <em>3</em> (Xbox ONE / Xbox Series X|S)', 'matchLevel': 'full', 'fullyHighlighted': False, 'matchedWords': ['hitma ... (1605 characters truncated) ... eractive A/S', 'matchLevel': 'none', 'matchedWords': []}, 'publisher_name': {'value': 'Io-Interactive A/S', 'matchLevel': 'none', 'matchedWords': []}}))]
(Background on this error at: https://sqlalche.me/e/14/rvf5)

In [ ]:
conn.commit()

In [ ]:
sqlite_connection.close()

In [ ]:
c.close
conn.close()